### ISSUE TITLE
Error when no bluetooth adapter

### ISSUE THREAD

**Issue by dlech** [mvidner/lignite#4]
I don't have built-in bluetooth, so after creating the bluetooth address config file, I get the following error

```
/home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection/bluetooth.rb:19:in `connect': No route to host - connect(2) for unknown address family 31 (Errno::EHOSTUNREACH)
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection/bluetooth.rb:19:in `initialize'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection.rb:8:in `new'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection.rb:8:in `rescue in create'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/connection.rb:5:in `create'
        from /home/david/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/lignite-0.1.0/lib/lignite/direct_commands.rb:5:in `initialize'
        from hello.rb:4:in `new'
        from hello.rb:4:in `<main>'
```

A friendly error message, such as "no Bluetooth or USB devices found", would be better.

**Comment by mvidner** [comment]
Ah, even my oldest machines have a built-in BT adapter, but I guess I can remove the kernel module to simulate the absence. (Note to self: `rmmod btusb` does it)

OK, I just need to poke a bit so that the library does not swallow too much details of other exceptions.
